"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const auth=require("../lib/crm-auth");
const {readSessionCookie}=require("../lib/crm-session-auth");
const {requiredRole,permitted}=require("../lib/crm-role-policy");
const {requireTrustedOrigin}=require("../lib/crm-csrf");
const {lookupSession,revokeSession,createSession}=require("../lib/crm-session-store");
const reply=()=>({statusCode:200,status(n){this.statusCode=n;return this},json(v){this.body=v;return this}});
const originReq=(method,origin,host="crm.example")=>({method,secure:true,get(k){return k==="origin"?origin:k==="host"?host:null}});
const csrf=(req)=>{let next=false;const res=reply();requireTrustedOrigin(req,res,()=>{next=true});return {next,status:res.statusCode}};
test("01 session tokens are 64 lowercase hex characters",()=>assert.match(auth.newSession().token,/^[0-9a-f]{64}$/));
test("02 separate sessions have distinct tokens",()=>assert.notEqual(auth.newSession().token,auth.newSession().token));
test("03 token hash matches SHA256",()=>{const s=auth.newSession();assert.equal(s.tokenHash,crypto.createHash("sha256").update(s.token).digest("hex"))});
test("04 session hash rejects missing token",()=>assert.equal(auth.hashSession(null),null));
test("05 session hash rejects uppercase token",()=>assert.equal(auth.hashSession("A".repeat(64)),null));
test("06 session hash rejects oversized token",()=>assert.equal(auth.hashSession("a".repeat(65)),null));
test("07 password verifier rejects malformed hex",()=>assert.equal(auth.verifyPassword("pass","salt","zz"),false));
test("08 password verifier rejects oversized password",()=>assert.equal(auth.verifyPassword("x".repeat(257),"salt","a".repeat(128)),false));
test("09 password verifier accepts correct scrypt digest",()=>{const salt="fixed-test-salt",pw="long-password";const hash=crypto.scryptSync(pw,salt,64).toString("hex");assert.equal(auth.verifyPassword(pw,salt,hash),true)});
test("10 password verifier rejects wrong password",()=>{const salt="fixed-test-salt",hash=crypto.scryptSync("correct",salt,64).toString("hex");assert.equal(auth.verifyPassword("incorrect",salt,hash),false)});
test("11 cookie is HttpOnly",()=>assert.equal(auth.cookieOptions().httpOnly,true));
test("12 cookie is Secure",()=>assert.equal(auth.cookieOptions().secure,true));
test("13 cookie is SameSite strict",()=>assert.equal(auth.cookieOptions().sameSite,"strict"));
test("14 cookie lifetime is eight hours",()=>assert.equal(auth.cookieOptions().maxAge,8*60*60*1000));
test("15 cookie parser ignores unrelated cookie",()=>assert.equal(readSessionCookie({headers:{cookie:"other=123"}}),null));
test("16 cookie parser accepts valid token in middle",()=>assert.equal(readSessionCookie({headers:{cookie:"a=1; crm_session="+"f".repeat(64)+"; b=2"}}),"f".repeat(64)));
test("17 draft POST requires master",()=>assert.equal(requiredRole("POST","/drafts"),"master"));
test("18 draft GET requires master",()=>assert.equal(requiredRole("GET","/drafts/42"),"master"));
test("19 draft DELETE requires owner",()=>assert.equal(requiredRole("DELETE","/drafts/42"),"owner"));
test("20 unknown role is denied",()=>assert.equal(permitted("guest","GET","/drafts/42"),false));
test("21 master cannot access owner routes",()=>assert.equal(permitted("master","GET","/dashboard"),false));
test("22 owner can access owner routes",()=>assert.equal(permitted("owner","GET","/dashboard"),true));
test("23 trusted same-origin POST is accepted",()=>assert.equal(csrf(originReq("POST","https://crm.example")).next,true));
test("24 cross-origin POST is rejected",()=>assert.equal(csrf(originReq("POST","https://attacker.example")).status,403));
test("25 POST without Origin is rejected",()=>assert.equal(csrf(originReq("POST",null)).status,403));
test("26 GET without Origin is accepted",()=>assert.equal(csrf(originReq("GET",null)).next,true));
test("27 missing session never queries database",async()=>{let called=false;const out=await lookupSession({query(){called=true}},null);assert.equal(out,null);assert.equal(called,false)});
test("28 invalid token cannot revoke a session",async()=>{let called=false;const out=await revokeSession({query(){called=true}},"bad");assert.equal(out,false);assert.equal(called,false)});
test("29 valid session lookup returns user",async()=>{const token="a".repeat(64),user={id:"test",role:"owner"};const db={query:async(sql,args)=>{assert.match(sql,/revoked_at IS NULL/);assert.equal(args[0],auth.hashSession(token));return {rows:[user]}}};assert.deepEqual(await lookupSession(db,token),user)});
test("30 session creation stores hash not raw token",async()=>{let params;await createSession({query:async(_sql,p)=>{params=p}}, "staff-1",{token:"secret",tokenHash:"hashed"});assert.deepEqual(params,["staff-1","hashed"])});
