"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const crypto=require("node:crypto");
const {makeLoginHandler}=require("../lib/crm-login-handler");
const {readSessionCookie,staffSessionMiddleware}=require("../lib/crm-session-auth");
const {requireTrustedOrigin}=require("../lib/crm-csrf");
let sequence=0;
function setup(options={}){
 const id=++sequence,login="operator"+id,password="correct-password-123456",salt="salt-"+id;
 const hash=crypto.scryptSync(password,salt,64).toString("hex");
 const calls=[];
 const db={query:async(sql,params)=>{calls.push({sql,params});if(options.throwDb)throw Error("private database secret");if(sql.includes("FROM crm_login_attempts"))return {rows:[]};if(sql.includes("FROM crm_staff WHERE"))return {rows:options.userMissing?[]:[{id:"staff-"+id,login,role:"owner",password_salt:salt,password_hash:hash}]};if(sql.startsWith("INSERT")){if(options.throwInsert&&sql.includes("crm_staff_sessions"))throw Error("insert failed");return {rowCount:1}};if(sql.startsWith("DELETE"))return {rowCount:1};throw Error("unexpected SQL")}};
 const res={statusCode:200,status(n){this.statusCode=n;return this},cookie(name,token,options){this.cookieData={name,token,options};return this},json(v){this.body=v;return this}};
 const req={body:{login,password},ip:"192.0.2."+(id%200+1)};
 return {db,res,req,calls,login,password};
}
const run=async (o={},change=()=>{})=>{const c=setup(o);change(c);await makeLoginHandler(c.db)(c.req,c.res);return c};
test("01 missing body fails closed",async()=>{const c=await run({},x=>{delete x.req.body});assert.equal(c.res.statusCode,401)});
test("02 missing login fails closed",async()=>{const c=await run({},x=>{delete x.req.body.login});assert.equal(c.res.statusCode,401)});
test("03 numeric login fails closed",async()=>{const c=await run({},x=>{x.req.body.login=123});assert.equal(c.res.statusCode,401)});
test("04 blank login fails closed",async()=>{const c=await run({},x=>{x.req.body.login=" "});assert.equal(c.res.statusCode,401)});
test("05 short login fails closed",async()=>{const c=await run({},x=>{x.req.body.login="ab"});assert.equal(c.res.statusCode,401)});
test("06 oversized login fails closed",async()=>{const c=await run({},x=>{x.req.body.login="a".repeat(101)});assert.equal(c.res.statusCode,401)});
test("07 invalid login punctuation fails closed",async()=>{const c=await run({},x=>{x.req.body.login="a@b.com"});assert.equal(c.res.statusCode,401)});
test("08 missing password fails closed",async()=>{const c=await run({},x=>{delete x.req.body.password});assert.equal(c.res.statusCode,401)});
test("09 numeric password fails closed",async()=>{const c=await run({},x=>{x.req.body.password=123456789012});assert.equal(c.res.statusCode,401)});
test("10 short password fails closed",async()=>{const c=await run({},x=>{x.req.body.password="short"});assert.equal(c.res.statusCode,401)});
test("11 oversized password fails closed",async()=>{const c=await run({},x=>{x.req.body.password="x".repeat(257)});assert.equal(c.res.statusCode,401)});
test("12 invalid input never queries database",async()=>{const c=await run({},x=>{x.req.body.password="x"});assert.equal(c.calls.length,0)});
test("13 unknown account returns generic credentials error",async()=>{const c=await run({userMissing:true});assert.equal(c.res.statusCode,401);assert.equal(c.res.body.error,"invalid_credentials")});
test("14 wrong password returns generic credentials error",async()=>{const c=await run({},x=>{x.req.body.password="wrong-password-123"});assert.equal(c.res.statusCode,401);assert.equal(c.res.body.error,"invalid_credentials")});
test("15 wrong password never creates session",async()=>{const c=await run({},x=>{x.req.body.password="wrong-password-123"});assert.equal(c.calls.filter(x=>x.sql.startsWith("INSERT")).length,0)});
test("16 database outage returns 503",async()=>{const c=await run({throwDb:true});assert.equal(c.res.statusCode,503)});
test("17 database outage does not leak internal details",async()=>{const c=await run({throwDb:true});assert.doesNotMatch(JSON.stringify(c.res.body),/private database secret/)});
test("18 session insert failure returns 503",async()=>{const c=await run({throwInsert:true});assert.equal(c.res.statusCode,503)});
test("19 session insert failure does not set cookie",async()=>{const c=await run({throwInsert:true});assert.equal(c.res.cookieData,undefined)});
test("20 successful login sets HttpOnly session",async()=>{const c=await run();assert.equal(c.res.statusCode,200);assert.equal(c.res.cookieData.options.httpOnly,true)});
test("21 successful login sets Secure session",async()=>{const c=await run();assert.equal(c.res.cookieData.options.secure,true)});
test("22 successful login never returns password",async()=>{const c=await run();assert.doesNotMatch(JSON.stringify(c.res.body),/correct-password/)});
test("23 successful login persists hashed token",async()=>{const c=await run();const insert=c.calls.find(x=>x.sql.startsWith("INSERT"));assert.equal(insert.params[1],crypto.createHash("sha256").update(c.res.cookieData.token).digest("hex"))});
test("24 valid cookie with trailing junk is rejected",()=>assert.equal(readSessionCookie({headers:{cookie:"crm_session="+"a".repeat(64)+"junk"}}),null));
test("25 CSRF check rejects cross-site mutation",()=>{let next=false;const req={method:"DELETE",secure:true,get:k=>k==="origin"?"https://attacker.example":"crm.example"};const res={status(n){this.code=n;return this},json(v){this.body=v}};requireTrustedOrigin(req,res,()=>{next=true});assert.equal(next,false);assert.equal(res.code,403)});
