"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const throttle=require("../lib/crm-login-throttle-db");
test("01 key is a SHA256 digest",()=>assert.match(throttle.keyFor("owner","192.0.2.1"),/^[0-9a-f]{64}$/));
test("02 login is case insensitive",()=>assert.equal(throttle.keyFor("OWNER","192.0.2.1"),throttle.keyFor("owner","192.0.2.1")));
test("03 key differs by IP",()=>assert.notEqual(throttle.keyFor("owner","192.0.2.1"),throttle.keyFor("owner","192.0.2.2")));
test("04 key differs by login",()=>assert.notEqual(throttle.keyFor("owner","192.0.2.1"),throttle.keyFor("master","192.0.2.1")));
test("05 key contains no raw login",()=>assert.doesNotMatch(throttle.keyFor("privateowner","192.0.2.1"),/privateowner/));
test("06 key contains no raw IP",()=>assert.doesNotMatch(throttle.keyFor("owner","192.0.2.1"),/192\.0\.2/));
test("07 default window is fifteen minutes",()=>assert.equal(throttle.WINDOW_SECONDS,900));
test("08 default maximum is five",()=>assert.equal(throttle.MAX_ATTEMPTS,5));
test("09 no attempts allows login",async()=>assert.equal(await throttle.allowed({query:async()=>({rows:[]})},"owner","ip"),true));
test("10 four attempts allow login",async()=>assert.equal(await throttle.allowed({query:async()=>({rows:[{failures:4}]})},"owner","ip"),true));
test("11 five attempts block login",async()=>assert.equal(await throttle.allowed({query:async()=>({rows:[{failures:5}]})},"owner","ip"),false));
test("12 six attempts block login",async()=>assert.equal(await throttle.allowed({query:async()=>({rows:[{failures:6}]})},"owner","ip"),false));
test("13 allowed query uses parameter",async()=>{let args;await throttle.allowed({query:async(_,p)=>{args=p;return {rows:[]}}},"owner","ip");assert.equal(args.length,1);assert.match(args[0],/^[a-f0-9]{64}$/)});
test("14 allowed query checks window expiry",async()=>{let sql;await throttle.allowed({query:async(s)=>{sql=s;return {rows:[]}}},"owner","ip");assert.match(sql,/15 minutes/)});
test("15 record failure is an atomic upsert",async()=>{let sql;await throttle.recordFailure({query:async(s)=>{sql=s}},"owner","ip");assert.match(sql,/ON CONFLICT/)});
test("16 upsert increments existing failures",async()=>{let sql;await throttle.recordFailure({query:async(s)=>{sql=s}},"owner","ip");assert.match(sql,/failures\+1/)});
test("17 upsert resets expired window",async()=>{let sql;await throttle.recordFailure({query:async(s)=>{sql=s}},"owner","ip");assert.match(sql,/THEN 1/)});
test("18 failure stores hashed key",async()=>{let args;await throttle.recordFailure({query:async(_,p)=>{args=p}},"owner","ip");assert.match(args[0],/^[a-f0-9]{64}$/)});
test("19 successful login clears key",async()=>{let sql;await throttle.clear({query:async(s)=>{sql=s}},"owner","ip");assert.match(sql,/DELETE FROM crm_login_attempts/)});
test("20 clear is parameterized",async()=>{let args;await throttle.clear({query:async(_,p)=>{args=p}},"owner","ip");assert.equal(args.length,1)});
test("21 missing database fails closed on allowed",async()=>await assert.rejects(throttle.allowed(null,"owner","ip"),/throttle_unavailable/));
test("22 missing database fails closed on record",async()=>await assert.rejects(throttle.recordFailure(null,"owner","ip"),/throttle_unavailable/));
test("23 missing database fails closed on clear",async()=>await assert.rejects(throttle.clear(null,"owner","ip"),/throttle_unavailable/));
test("24 database failure propagates",async()=>await assert.rejects(throttle.allowed({query:async()=>{throw Error("db unavailable")}},"owner","ip"),/db unavailable/));
test("25 database failure on record propagates",async()=>await assert.rejects(throttle.recordFailure({query:async()=>{throw Error("db unavailable")}},"owner","ip"),/db unavailable/));
